name: UHC
main: fr.flv92.UHC
version: 1.0
author: Flv92

commands:
  uhc-addPlayer:
    description: Add players to UHC
    usage: /uhc-addPlayer [ @a | player1 player2 player3 ... ] 
  uhc-list:
    description: List UHC players
    usage: /uhc-list
  uhc-start:
    description: Start the game
    usage: /uhc-start [mapSize]
  uhc-addSpawn:
    description: Add a spawn
    usage: /uhc-addSpawn (and point an empty sign)
  